### ISSUE TITLE
Select more than one media query [request] 

### ISSUE THREAD

**Issue by battaglr** [kjvalencik/gulp-mq-remove#3]
First of all, awesome work!

While using it —and since I'm using a mobile-first approach— I encountered myself needing to select more than one media query.

I'll try to illustrate the use-case with a simple example:

``` css
.component {
  width: 100%;
}

@media (min-width: 480px) {
  .component {
    width: 50%;
    float: left;
  }
}

@media (min-width: 768px) {
  .component {
    width: 25%;
  }
}
```

In this case, I would want to select both media queries, since for the "large" view to render as I want I need a property I defined in a previous media query —the `float`.

_I know this particular use-case could be solved in many different ways, I'm just trying to keep it simple._

What do you think? Is selecting multiple media queries something you would like to support?

Thanks!

**Comment by kjvalencik** [comment]
@battaglr, sure. It could be added fairly easily. TBH, I haven't looked at this code in a long time and I'm not sure when I might get a chance. But, if you wanted to take a shot at it:
1. Update the `query` argument to be an array of `[query]`.
2. Update the match to look for at least one match:

https://github.com/kjvalencik/gulp-mq-remove/blob/2a3fdf2820be282b6b6f132c3ff6a8b826b4b8eb/lib/index.js#L32

``` js
!queries.some(mediaQuery.match.bind(mediaQuery, rule.media))
```

**Comment by kjvalencik** [comment]
@battaglr, taking a second look at this. I'm not quite sure what you mean. If you define your query as

`{ width : "768px" }`

it should match both of these queries. Since `768` is larger than both of those rules.

https://github.com/kjvalencik/gulp-mq-remove/blob/master/lib/test/test.css
https://github.com/kjvalencik/gulp-mq-remove/blob/master/lib/test/results.css

**Comment by battaglr** [comment]
Hum, I see. It's weird since I'm doing exactly that in my code —using `{ width : "768px" }` as you said— and I just get the code of that particular media query as output. But the test proves me wrong. Let me check if I'm doing something wrong.

**Comment by kjvalencik** [comment]
@battaglr, also check orientation and screen rules that might not be matching. Is the code you pasted sufficient to reproduce?

I just ran your example through and the response was as expected:

``` css
.component {
  width: 100%;
}

.component {
  width: 50%;
  float: left;
}

.component {
  width: 25%;
}
```
